<?php

namespace App\Repositories\Plan;

use App\Models\Plan;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Model;

class PlanRepository extends BaseRepository implements PlanRepositoryInterface
{

    public function __construct(Plan $model)
    {
        parent::__construct($model);
    }

    public function getModel(): Plan
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

}
